server:
  port: 7068

spring:
  application:
    name: xm-agent

openai:
  api-key: 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
  model: qwen/qwen3-0.6b-04-28:free
  timeout: 60s
  base-url: https://openrouter.ai/api/v1/